In [1]:
import torch
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
torch.__version__

C:\Users\Tanvir Kabir\AppData\Local\Temp\ipykernel_14232\1586056223.py:4: DeprecationWarning: 
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466
        
  import pandas as pd


'2.1.0'

In [2]:
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [3]:
tensor*10

tensor([10, 20, 30])

In [4]:
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [5]:
torch.matmul(tensor, tensor)

tensor(14)

In [6]:
x = torch.arange(1.,10.)
x,x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [7]:
#reshape
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [8]:
#view
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [9]:
x.device

device(type='cpu')

In [ ]:
#Stack tensors
x_stacked = torch.stack([x,x,x,x],dim=1)
x_stacked

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [13]:
x_reshaped.shape

torch.Size([1, 9])

In [14]:
x_reshaped

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [15]:
# Squeeze
x_squeezed = x_reshaped.squeeze()
x_squeezed

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [16]:
x_squeezed.shape

torch.Size([9])

In [20]:
# Unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
x_unsqueezed

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [24]:
# Permute
x_original = torch.rand(size=(224,224,3))
x_permuted = x_original.permute(2,0,1) #shifts axis

print(f"Prev Shape:{x_original.shape} -> New SHape:{x_permuted.shape}")

Prev Shape:torch.Size([224, 224, 3]) -> New SHape:torch.Size([3, 224, 224])


In [25]:
x = torch.arange(1,10).reshape(1,3,3)
x,x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [26]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [27]:
x[0][0]

tensor([1, 2, 3])

In [30]:
x[0][2][2]

tensor(9)

In [31]:
x[:,0]

tensor([[1, 2, 3]])

In [32]:
x[:,:,1]

tensor([[2, 5, 8]])

In [33]:
# get 0 dim but index the value of the first and second dim
x[:,1,1]

tensor([5])

In [ ]:
import torch
import numpy as np

array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array)

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [39]:
array.dtype, tensor.dtype

(dtype('float64'), torch.float64)

In [41]:
torch.arange(1.,10.).dtype

torch.float32

In [46]:
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [47]:
# random seed -> random flavours

randA = torch.rand(3,4)
randB = torch.rand(3,4)

print(randA)
print(randB)
print(randA == randB)

tensor([[0.3634, 0.0905, 0.2049, 0.6142],
        [0.1112, 0.6778, 0.0337, 0.4716],
        [0.5238, 0.7650, 0.9201, 0.1621]])
tensor([[0.8038, 0.0784, 0.5577, 0.3218],
        [0.1496, 0.0099, 0.6344, 0.6835],
        [0.2321, 0.4575, 0.7155, 0.6665]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [48]:
torch.cuda.is_available()

True

In [52]:
device = "cuda" if torch.cuda.is_available() else "cpu"

In [1]:
device

NameError: name 'device' is not defined

In [54]:
torch.cuda.device_count()

1