In [5]:
import torch
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
torch.__version__

C:\Users\Tanvir Kabir\AppData\Local\Temp\ipykernel_12620\1586056223.py:4: DeprecationWarning: 
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466
        
  import pandas as pd


'2.1.0'

Introduction to Tensors

In [7]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [8]:
scalar.ndim

0

In [9]:
scalar.item()

7

In [10]:
vector = torch.tensor([1,2,3,4,5])
vector

tensor([1, 2, 3, 4, 5])

In [11]:
vector.ndim

1

In [12]:
vector.shape

torch.Size([5])

In [ ]:
MATRIX = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
MATRIX

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[0]

tensor([1, 2, 3])

In [ ]:
MATRIX[1]

tensor([4, 5, 6])

In [ ]:
MATRIX.shape

torch.Size([3, 3])

In [19]:
#TENSOR
TENSOR = torch.Tensor([[[1,2,3],[4,5,6],[7,8,9]]])
TENSOR

tensor([[[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]])

In [20]:
TENSOR.ndim

3

In [21]:
TENSOR.shape

torch.Size([1, 3, 3])

In [22]:
TENSOR[0]

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [ ]:
# random tensor
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.8090, 0.9958, 0.6929, 0.6749],
        [0.9207, 0.7030, 0.9975, 0.8821],
        [0.7284, 0.2728, 0.1399, 0.2605]])

In [25]:
# random tensor with similar shape to an image tensor
image_tensor = torch.rand(size=(3, 256, 256))
image_tensor.shape
# image_tensor.ndim

torch.Size([3, 256, 256])