In [1]:
import torch
import numpy as np

In [3]:
torch.cuda.is_available()

True

In [4]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

In [5]:
device

device(type='cuda')

In [7]:
# Tensor (Default on the CPU)
tensor = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(tensor, tensor.device)

tensor([[1, 2, 3],
        [4, 5, 6]]) cpu


In [8]:
tensor_on_gpu = tensor.to(device)
print(tensor_on_gpu, tensor_on_gpu.device)

tensor([[1, 2, 3],
        [4, 5, 6]], device='cuda:0') cuda:0


In [11]:
#Move the tensor back to the CPU
tensor_on_cpu = tensor_on_gpu.cpu()
print(tensor_on_cpu, tensor_on_cpu.device)

tensor([[1, 2, 3],
        [4, 5, 6]]) cpu
